pipeline:
  sftp_cache:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git

  build:
    image: scalaplatform/scala:0.6
    pull: true
    volumes:
      - /platform:/keys
    pull: true
    commands:
      - sbt clean sporesJS/test sporesJVM/test spores-serialization/test sporesJVM/publishLocal sporesJS/publishLocal spores-serialization/publishLocal playgroundJS/run playgroundJVM/run

  sftp_cache:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
