language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION 'project spores-core' clean test
  - sbt ++$TRAVIS_SCALA_VERSION 'project spores-spark' clean test
  - sbt ++$TRAVIS_SCALA_VERSION 'project spores-pickling' clean test
scala:
  - 2.11.7
jdk:
  - oraclejdk8
  - oraclejdk7
notifications:
  email:
    - jorgevc@fastmail.es
