language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION 'project spores-core' clean test
  - sbt ++$TRAVIS_SCALA_VERSION 'project spores-pickling' clean test
scala:
  - 2.11.6
jdk:
  - oraclejdk8
  - openjdk7
  - oraclejdk7
notifications:
  email:
    - heather.miller@epfl.ch
    - philipp.haller@a3.epfl.ch
