language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION 'project spores-core' test 'project spores-spark' test 'project spores-pickling' test
scala:
  - 2.11.7
jdk:
  - oraclejdk8
  - oraclejdk7
notifications:
  email:
    - jorgevc@fastmail.es
